### ISSUE TITLE
editcp program crash while downloading from md-380

### ISSUE THREAD

**Issue by sadatoni** [DaleFarnsworth/codeplug#28]
Program crash while downloading from MD-380

panic: runtime error: index out of range

goroutine 1 [running, locked to thread]:
github.com/dalefarnsworth/codeplug/stdfu.errorFromErrno(0xedcc03e6, 0x148f9d50, 0x4)
	/media/sf_GOPATH0/src/github.com/dalefarnsworth/codeplug/stdfu/stdfu_windows.go:155 +0xe4
github.com/dalefarnsworth/codeplug/stdfu.(*StDfu).Upload(0x148f9ad4, 0x2, 0x14984400, 0x400, 0x400, 0x400, 0x84fb0c)
	/media/sf_GOPATH0/src/github.com/dalefarnsworth/codeplug/stdfu/stdfu_windows.go:265 +0x7a
github.com/dalefarnsworth/codeplug/dfu.(*Dfu).readFlashTo(0x14946b60, 0x0, 0x40000, 0x853900, 0x149641e0, 0x74aba0, 0x14923d01)
	/media/sf_GOPATH0/src/github.com/dalefarnsworth/codeplug/dfu/dfu.go:913 +0x27e
github.com/dalefarnsworth/codeplug/dfu.(*Dfu).ReadCodeplug(0x14946b60, 0x14ae8000, 0x40000, 0x40000, 0x40000, 0x40000)
	/media/sf_GOPATH0/src/github.com/dalefarnsworth/codeplug/dfu/dfu.go:1215 +0x70
github.com/dalefarnsworth/codeplug/codeplug.(*Codeplug).ReadRadio(0x14976280, 0x14946b40, 0x0, 0x0)
	/media/sf_GOPATH0/src/github.com/dalefarnsworth/codeplug/codeplug/codeplug.go:2249 +0x102
main.(*editor).addRadioMenu.func1()
	/media/sf_GOPATH0/src/github.com/dalefarnsworth/codeplug/editcp/radio.go:280 +0x15b
github.com/dalefarnsworth/codeplug/ui.(*Menu).AddAction.func1(0x74ac00)
	/media/sf_GOPATH0/src/github.com/dalefarnsworth/codeplug/ui/ui.go:1874 +0x19
github.com/therecipe/qt/widgets.callbackQAction_Triggered(0x35112b60, 0x427600)
	/home/user/work/src/github.com/therecipe/qt/widgets/widgets-minimal.go:2757 +0x64
github.com/therecipe/qt/widgets._cgoexpwrap_482a80a72e1e_callbackQAction_Triggered(0x35112b60, 0x25cd000)
	_cgo_gotypes.go:19299 +0x2a
github.com/therecipe/qt/widgets._Cfunc_QApplication_QApplication_Exec(0x0)
	_cgo_gotypes.go:2898 +0x3b
github.com/therecipe/qt/widgets.(*QApplication).Exec(0x1499b320, 0x14ad8d40)
	/home/user/work/src/github.com/therecipe/qt/widgets/widgets-minimal.go:3387 +0x1a
github.com/dalefarnsworth/codeplug/ui.(*App).Exec(0x1499b320)
	/media/sf_GOPATH0/src/github.com/dalefarnsworth/codeplug/ui/ui.go:76 +0x23
main.main()
	/media/sf_GOPATH0/src/github.com/dalefarnsworth/codeplug/editcp/editcp.go:326 +0x2d1

**Comment by DaleFarnsworth** [comment]
Thank you for taking the time to report this bug.  Can you give me some additional context to help me reproduce it?

What version of editcp?
Windows 7 or windows 10?
Were you attempting to download (read) a codeplug from the MD-380?

Thanks.
